version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=host=db user=user dbname=musicdb password=password sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
