version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080" 
    environment:
      - DATABASE_URL=${DATABASE_URL} 
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-musicdb}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
